- name: "Creates backend app directory"
  file:
    path: /backend
    state: directory

- name: "Copying the build"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /backend


- name: "Unzip backend files to correct directory"
  shell: |
    cd /backend
    tar -zxvf artifact.tar.gz
    rm -rf artifact.tar.gz

- name: "Install dependencies for project"
  shell: |
    cd /backend
    npm install
    pm2 stop default
    pm2 start npm -- start
  environment:
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

#- name:  start app
#  command:  pm2 start main.js
#  args:
#    chdir: /backend/dest
#  environment:
#      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
#      TYPEORM_MIGRATIONS_DIR: "./migrations"
#      TYPEORM_MIGRATIONS: "./migrations/*.js"
#      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
#      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
#      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
#      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
#      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
#      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"