- name: "Copying the build"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /
- name: Extract artifact.tar.gz /backend
  become: true
  unarchive:
    src: /artifact.tar.gz
    dest: /backend
    remote_src: yes
- name: Install "build" 
  become: true 
  npm:
    name: running install npm backend
    path: /backend
  
 - name: start pm2 process
   command: 'pm2 start npm -- start'
   become: yes