- name: "Copying the build"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /
- name: Extract artifact.tar.gz /backend
  become: true
  unarchive:
    src: /artifact.tar.gz
    dest: /backend
    remote_src: yes